### ISSUE TITLE
Shadow on hover covers the text

### ISSUE THREAD

**Issue by vikas-parashar** [Parbhat/Python-Pedia#12]
Hey,

I have spotted some minor issues which I found important as UI/UX point of view. Shadow on hover is covering some text from content, reducing it little bit would solve it. and rotating gear doesn't go with flow of rest of the page, Static gear will also solve issue of rotating shadow.

**Comment by Parbhat** [comment]
@vikas-parashar thanks for reporting the issue. I also think using static gear will be a better option.

**Comment by NiclasEriksen** [comment]
I also vote for a static gear, the animation looks great but it stands out too much. It's as if embedded systems is where all the action is. Either animate all icons, or none, for consistency.

**Comment by Parbhat** [comment]
@vikas-parashar @NiclasEriksen thanks for reporting the issue. Gear icon is changed to static.
