### ISSUE TITLE
Replace contribute block on Homepage with Community section.

### ISSUE THREAD

**Issue by Parbhat** [Parbhat/Python-Pedia#36]
Contribution link is provided in the header and footer. So, it would be better to replace the last block Contribute with Community section.This section will contain the following:

* Links to different Pycons organised worldwide.
* links to local Python meetup groups.
* Links to specific conferences like Djangocon, PyData etc.

Any other links to Python Community at one place.

**Comment by mbj36** [comment]
@Parbhat  
so we need to create a new html page(community.html) and add various links in it ?

**Comment by Parbhat** [comment]
@mbj36 You need to create an HTML and Markdown file. The content will be fetched from markdown file. You can see the other blocks for example.

**Comment by mbj36** [comment]
@Parbhat  
okay! i am working on it :)
Can you provide some links from your side too ?

**Comment by Parbhat** [comment]
This is the list of Pycons - http://www.pycon.org/

**Comment by mbj36** [comment]
:+1:
