### ISSUE TITLE
Site: Embedded Python: Shadow misbehaves on mover hover

### ISSUE THREAD

**Issue by moigagoo** [Parbhat/Python-Pedia#5]
The shadow should point always to the same direction. Instead, it moves as the gear rotates. http://i.imgur.com/FIpYWUb.png

**Comment by Parbhat** [comment]
hello @moigagoo, this is the intended behaviour as shadow is generated by text-shadow property. The gear icon has font awesome fa-spin class so the shadow is generated as the gear rotates.

**Comment by moigagoo** [comment]
From the implementation point of view, yes, this is expected behavior. However, from the visitor's point of view, it definitely looks weird and buggy. Maybe, 

Still, it's up to you to decide whether it's bug or a feature. Unfortunately, I'm not a front-end developer, so I can't propose a fix.

**Comment by moigagoo** [comment]
*Maybe, it's the implementation that should be changed to suit the design, not vice versa.

**Comment by moigagoo** [comment]
BTW, thank you for the great job you've done!

**Comment by Parbhat** [comment]
@moigagoo thanks, I will take a closer look to correct the behaviour.

**Comment by Parbhat** [comment]
@moigagoo Gear icon changed to static.
